FUNCTION Z_TA_05_SELECT.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(NAMEDISCIPLINA) TYPE  ZDISCIPLINA OPTIONAL
*"  EXPORTING
*"     REFERENCE(ZTA05_GRADE_T) TYPE  ZTA05_GRADE_T
*"     REFERENCE(SUBRC) TYPE  SY-SUBRC
*"----------------------------------------------------------------------

DATA LV_NOME TYPE ZTA05_DISCIPLINA-NAMEDISCIPLINA.
CONCATENATE '%' NAMEDISCIPLINA '%' INTO LV_NOME.

SELECT A~NAMEDISCIPLINA B~NAMECURSO B~SEMESTRE
  INTO TABLE ZTA05_GRADE_T
  FROM ZTA05_GRADE AS G
  INNER JOIN ZTA05_CURSO AS B ON G~FK_CURSO = B~CODCURSO
  INNER JOIN ZTA05_DISCIPLINA AS A ON G~FK_DISCIPLINA = A~CODDISCI
  WHERE NAMEDISCIPLINA LIKE LV_NOME.

SUBRC = SY-SUBRC.

ENDFUNCTION.